# Generated by Django 4.2 on 2024-09-17 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_profile_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=userauths.models.ShortUUIDField(default=userauths.models.ShortUUIDField.generate_shortuuid, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
