# Generated by Django 4.2 on 2024-11-06 18:12

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_profile_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=userauths.models.ShortUUIDField(default=userauths.models.ShortUUIDField.generate_shortuuid, max_length=22, unique=True),
        ),
    ]
